imaging:
  contrast: 1.2
  sharpen_sigma: 1.0
  sharpen_amount: 1.5
  edge_threshold: 50
  resolution_dpi: 300
  temp_dir: "/tmp/balistica"
  default_resolution: 1200dpi
  min_quality: 95
  formats: [".png", ".jpg", ".tiff"]
  max_file_size: 10MB


features:
  hu_moments_scaling: logarithmic
  adaptive_threshold:
    block_size: 11
    c_constant: 2

chroma:
  color_threshold: 0.05
  sample_size: 20

server:
  address: ":8080"
  timeout:
    read: 5s
    write: 10s
    idle: 15s

python:
  enabled: true
  script_path: "py_services/feature_extractor.py"
  virtual_env: "balistics-env"
