app:
  name: "Ballistic Analysis System"
  version: "0.1.0"
  environment: "development"  # development, staging, production

server:
  port: "8080"

logging:  # Nueva sección para configuración de logging
  level: "info"  # debug, info, warn, error
  output: "stdout"  # stdout o file
  file_path: "logs/app.log"  # solo si output=file

python:  # Nueva sección para servicio Python
  timeout: "30s"  # timeout para ejecución de scripts Python

imaging:
  base_path: "./images"
  output_path: "./output"
  # Nuevos parámetros para procesamiento balístico
  reference_scale: 0.05  # mm/pixel
  min_keypoints: 50
  match_threshold: 0.7

chromadb:  # Nueva sección para ChromaDB
  host: "localhost"
  port: 8000
  collection: "cartridge_cases"