imaging:
  contrast: 1.2
  sharpen_sigma: 1.0
  sharpen_amount: 1.5
  edge_threshold: 50
  resolution_dpi: 300

chroma:
  color_threshold: 0.05
  sample_size: 20

server:
  address: ":8080"
  timeout:
    read: 5s
    write: 10s
    idle: 15s